### ISSUE TITLE
Update this to use Python 3

### ISSUE THREAD

**Issue by ekozlowski** [ekozlowski/celery_play#1]

**Comment by ekozlowski** [comment]
Getting error with install:

Collecting wsgiref==0.1.2
  Downloading wsgiref-0.1.2.zip (37 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/ekozlowski/celery_play/image_resizer/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hz/mg_p4ltj0hd33kgd3t7gr7hm0000gn/T/pip-install-ei2cj6oo/wsgiref/setup.py'"'"'; __file__='"'"'/private/var/folders/hz/mg_p4ltj0hd33kgd3t7gr7hm0000gn/T/pip-install-ei2cj6oo/wsgiref/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/hz/mg_p4ltj0hd33kgd3t7gr7hm0000gn/T/pip-pip-egg-info-8o19cy4q
         cwd: /private/var/folders/hz/mg_p4ltj0hd33kgd3t7gr7hm0000gn/T/pip-install-ei2cj6oo/wsgiref/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hz/mg_p4ltj0hd33kgd3t7gr7hm0000gn/T/pip-install-ei2cj6oo/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/private/var/folders/hz/mg_p4ltj0hd33kgd3t7gr7hm0000gn/T/pip-install-ei2cj6oo/wsgiref/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
